# Whether if the worlds list below should be a whitelist or not
# If whitelist mode is on, all worlds are allowed to spawn phantoms by default unless they are in the worlds list
# If whitelist mode is off, only the worlds in the worlds list are allowed to spawn phantoms
whitelist: false
# Which worlds should be blacklisted (or whitelist if whitelist is true)
worlds:
  - "Example World"
# What spawn reasons should be allowed
# Do not change this unless you know what you are doing
allowedSpawnReasons:
  - SPAWNER_EGG # Allow for spawner eggs to spawn phantoms
  - SPAWNER # Allow for spawners to spawn phantoms
  - CUSTOM # Allow for other plugins trying to spawn phantoms